# Default Config File for Dynamic Shops Plugin
# Default Modifier: 100, lower = More change per sale | higher = less change per sale
# I would recommend basing on average players per day on server; if you get about 10 per day then the value should be 100, if you get about 1 per day then the value should be 10.
#Prices: "-1" indicates disabled, use "/DSA set name price" to enable

message: Dynamic Shops plugin Developed by idiotonastic.

GUI: true

Modifier: 100

ACACIA_BOAT: -1
ACACIA_BUTTON: -1
ACACIA_DOOR: -1
ACACIA_FENCE: -1
ACACIA_FENCE_GATE: -1
ACACIA_LEAVES: -1
ACACIA_LOG: -1
ACACIA_PLANKS: -1
ACACIA_PRESSURE_PLATE: -1
ACACIA_SAPLING: -1
ACACIA_SIGN: -1
ACACIA_SLAB: -1
ACACIA_STAIRS: -1
ACACIA_TRAPDOOR: -1
ACACIA_WALL_SIGN: -1
ACACIA_WOOD: -1
ACTIVATOR_RAIL: -1
AIR: -1
ALLIUM: -1
ANDESITE: -1
ANDESITE_SLAB: -1
ANDESITE_STAIRS: -1
ANDESITE_WALL: -1
ANVIL: -1
APPLE: -1
ARMOR_STAND: -1
ARROW: -1
ATTACHED_MELON_STEM: -1
ATTACHED_PUMPKIN_STEM: -1
AZURE_BLUET: -1
BAKED_POTATO: -1
BAMBOO: -1
BAMBOO_SAPLING: -1
BARREL: -1
BARRIER: -1
BAT_SPAWN_EGG: -1
BEACON: -1
BEDROCK: -1
BEE_NEST: -1
BEE_SPAWN_EGG: -1
BEEF: -1
BEEHIVE: -1
BEETROOT: -1
BEETROOT_SEEDS: -1
BEETROOT_SOUP: -1
BEETROOTS: -1
BELL: -1
BIRCH_BOAT: -1
BIRCH_BUTTON: -1
BIRCH_DOOR: -1
BIRCH_FENCE: -1
BIRCH_FENCE_GATE: -1
BIRCH_LEAVES: -1
BIRCH_LOG: -1
BIRCH_PLANKS: -1
BIRCH_PRESSURE_PLATE: -1
BIRCH_SAPLING: -1
BIRCH_SIGN: -1
BIRCH_SLAB: -1
BIRCH_STAIRS: -1
BIRCH_TRAPDOOR: -1
BIRCH_WALL_SIGN: -1
BIRCH_WOOD: -1
BLACK_BANNER: -1
BLACK_BED: -1
BLACK_CARPET: -1
BLACK_CONCRETE: -1
BLACK_CONCRETE_POWDER: -1
BLACK_DYE: -1
BLACK_GLAZED_TERRACOTTA: -1
BLACK_SHULKER_BOX: -1
BLACK_STAINED_GLASS: -1
BLACK_STAINED_GLASS_PANE: -1
BLACK_TERRACOTTA: -1
BLACK_WALL_BANNER: -1
BLACK_WOOL: -1
BLAST_FURNACE: -1
BLAZE_POWDER: -1
BLAZE_ROD: -1
BLAZE_SPAWN_EGG: -1
BLUE_BANNER: -1
BLUE_BED: -1
BLUE_CARPET: -1
BLUE_CONCRETE: -1
BLUE_CONCRETE_POWDER: -1
BLUE_DYE: -1
BLUE_GLAZED_TERRACOTTA: -1
BLUE_ICE: -1
BLUE_ORCHID: -1
BLUE_SHULKER_BOX: -1
BLUE_STAINED_GLASS: -1
BLUE_STAINED_GLASS_PANE: -1
BLUE_TERRACOTTA: -1
BLUE_WALL_BANNER: -1
BLUE_WOOL: -1
BONE: -1
BONE_BLOCK: -1
BONE_MEAL: -1
BOOK: -1
BOOKSHELF: -1
BOW: -1
BOWL: -1
BRAIN_CORAL: -1
BRAIN_CORAL_BLOCK: -1
BRAIN_CORAL_FAN: -1
BRAIN_CORAL_WALL_FAN: -1
BREAD: -1
BREWING_STAND: -1
BRICK: -1
BRICK_SLAB: -1
BRICK_STAIRS: -1
BRICK_WALL: -1
BRICKS: -1
BROWN_BANNER: -1
BROWN_BED: -1
BROWN_CARPET: -1
BROWN_CONCRETE: -1
BROWN_CONCRETE_POWDER: -1
BROWN_DYE: -1
BROWN_GLAZED_TERRACOTTA: -1
BROWN_MUSHROOM: -1
BROWN_MUSHROOM_BLOCK: -1
BROWN_SHULKER_BOX: -1
BROWN_STAINED_GLASS: -1
BROWN_STAINED_GLASS_PANE: -1
BROWN_TERRACOTTA: -1
BROWN_WALL_BANNER: -1
BROWN_WOOL: -1
BUBBLE_COLUMN: -1
BUBBLE_CORAL: -1
BUBBLE_CORAL_BLOCK: -1
BUBBLE_CORAL_FAN: -1
BUBBLE_CORAL_WALL_FAN: -1
BUCKET: -1
CACTUS: -1
CAKE: -1
CAMPFIRE: -1
CARROT: -1
CARROT_ON_A_STICK: -1
CARROTS: -1
CARTOGRAPHY_TABLE: -1
CARVED_PUMPKIN: -1
CAT_SPAWN_EGG: -1
CAULDRON: -1
CAVE_AIR: -1
CAVE_SPIDER_SPAWN_EGG: -1
CHAIN_COMMAND_BLOCK: -1
CHAINMAIL_BOOTS: -1
CHAINMAIL_CHESTPLATE: -1
CHAINMAIL_HELMET: -1
CHAINMAIL_LEGGINGS: -1
CHARCOAL: -1
CHEST: -1
CHEST_MINECART: -1
CHICKEN: -1
CHICKEN_SPAWN_EGG: -1
CHIPPED_ANVIL: -1
CHISELED_QUARTZ_BLOCK: -1
CHISELED_RED_SANDSTONE: -1
CHISELED_SANDSTONE: -1
CHISELED_STONE_BRICKS: -1
CHORUS_FLOWER: -1
CHORUS_FRUIT: -1
CHORUS_PLANT: -1
CLAY: -1
CLAY_BALL: -1
CLOCK: -1
COAL: -1
COAL_BLOCK: -1
COAL_ORE: -1
COARSE_DIRT: -1
COBBLESTONE: -1
COBBLESTONE_SLAB: -1
COBBLESTONE_STAIRS: -1
COBBLESTONE_WALL: -1
COBWEB: -1
COCOA: -1
COCOA_BEANS: -1
COD: -1
COD_BUCKET: -1
COD_SPAWN_EGG: -1
COMMAND_BLOCK: -1
COMMAND_BLOCK_MINECART: -1
COMPARATOR: -1
COMPASS: -1
COMPOSTER: -1
CONDUIT: -1
COOKED_BEEF: -1
COOKED_CHICKEN: -1
COOKED_COD: -1
COOKED_MUTTON: -1
COOKED_PORKCHOP: -1
COOKED_RABBIT: -1
COOKED_SALMON: -1
COOKIE: -1
CORNFLOWER: -1
COW_SPAWN_EGG: -1
CRACKED_STONE_BRICKS: -1
CRAFTING_TABLE: -1
CREEPER_BANNER_PATTERN: -1
CREEPER_HEAD: -1
CREEPER_SPAWN_EGG: -1
CREEPER_WALL_HEAD: -1
CROSSBOW: -1
CUT_RED_SANDSTONE: -1
CUT_RED_SANDSTONE_SLAB: -1
CUT_SANDSTONE: -1
CUT_SANDSTONE_SLAB: -1
CYAN_BANNER: -1
CYAN_BED: -1
CYAN_CARPET: -1
CYAN_CONCRETE: -1
CYAN_CONCRETE_POWDER: -1
CYAN_DYE: -1
CYAN_GLAZED_TERRACOTTA: -1
CYAN_SHULKER_BOX: -1
CYAN_STAINED_GLASS: -1
CYAN_STAINED_GLASS_PANE: -1
CYAN_TERRACOTTA: -1
CYAN_WALL_BANNER: -1
CYAN_WOOL: -1
DAMAGED_ANVIL: -1
DANDELION: -1
DARK_OAK_BOAT: -1
DARK_OAK_BUTTON: -1
DARK_OAK_DOOR: -1
DARK_OAK_FENCE: -1
DARK_OAK_FENCE_GATE: -1
DARK_OAK_LEAVES: -1
DARK_OAK_LOG: -1
DARK_OAK_PLANKS: -1
DARK_OAK_PRESSURE_PLATE: -1
DARK_OAK_SAPLING: -1
DARK_OAK_SIGN: -1
DARK_OAK_SLAB: -1
DARK_OAK_STAIRS: -1
DARK_OAK_TRAPDOOR: -1
DARK_OAK_WALL_SIGN: -1
DARK_OAK_WOOD: -1
DARK_PRISMARINE: -1
DARK_PRISMARINE_SLAB: -1
DARK_PRISMARINE_STAIRS: -1
DAYLIGHT_DETECTOR: -1
DEAD_BRAIN_CORAL: -1
DEAD_BRAIN_CORAL_BLOCK: -1
DEAD_BRAIN_CORAL_FAN: -1
DEAD_BRAIN_CORAL_WALL_FAN: -1
DEAD_BUBBLE_CORAL: -1
DEAD_BUBBLE_CORAL_BLOCK: -1
DEAD_BUBBLE_CORAL_FAN: -1
DEAD_BUBBLE_CORAL_WALL_FAN: -1
DEAD_BUSH: -1
DEAD_FIRE_CORAL: -1
DEAD_FIRE_CORAL_BLOCK: -1
DEAD_FIRE_CORAL_FAN: -1
DEAD_FIRE_CORAL_WALL_FAN: -1
DEAD_HORN_CORAL: -1
DEAD_HORN_CORAL_BLOCK: -1
DEAD_HORN_CORAL_FAN: -1
DEAD_HORN_CORAL_WALL_FAN: -1
DEAD_TUBE_CORAL: -1
DEAD_TUBE_CORAL_BLOCK: -1
DEAD_TUBE_CORAL_FAN: -1
DEAD_TUBE_CORAL_WALL_FAN: -1
DEBUG_STICK: -1
DETECTOR_RAIL: -1
DIAMOND: -1
DIAMOND_AXE: -1
DIAMOND_BLOCK: -1
DIAMOND_BOOTS: -1
DIAMOND_CHESTPLATE: -1
DIAMOND_HELMET: -1
DIAMOND_HOE: -1
DIAMOND_HORSE_ARMOR: -1
DIAMOND_LEGGINGS: -1
DIAMOND_ORE: -1
DIAMOND_PICKAXE: -1
DIAMOND_SHOVEL: -1
DIAMOND_SWORD: -1
DIORITE: -1
DIORITE_SLAB: -1
DIORITE_STAIRS: -1
DIORITE_WALL: -1
DIRT: -1
DISPENSER: -1
DOLPHIN_SPAWN_EGG: -1
DONKEY_SPAWN_EGG: -1
DRAGON_BREATH: -1
DRAGON_EGG: -1
DRAGON_HEAD: -1
DRAGON_WALL_HEAD: -1
DRIED_KELP: -1
DRIED_KELP_BLOCK: -1
DROPPER: -1
DROWNED_SPAWN_EGG: -1
EGG: -1
ELDER_GUARDIAN_SPAWN_EGG: -1
ELYTRA: -1
EMERALD: -1
EMERALD_BLOCK: -1
EMERALD_ORE: -1
ENCHANTED_BOOK: -1
ENCHANTED_GOLDEN_APPLE: -1
ENCHANTING_TABLE: -1
END_CRYSTAL: -1
END_GATEWAY: -1
END_PORTAL: -1
END_PORTAL_FRAME: -1
END_ROD: -1
END_STONE: -1
END_STONE_BRICK_SLAB: -1
END_STONE_BRICK_STAIRS: -1
END_STONE_BRICK_WALL: -1
END_STONE_BRICKS: -1
ENDER_CHEST: -1
ENDER_EYE: -1
ENDER_PEARL: -1
ENDERMAN_SPAWN_EGG: -1
ENDERMITE_SPAWN_EGG: -1
EVOKER_SPAWN_EGG: -1
EXPERIENCE_BOTTLE: -1
FARMLAND: -1
FEATHER: -1
FERMENTED_SPIDER_EYE: -1
FERN: -1
FILLED_MAP: -1
FIRE: -1
FIRE_CHARGE: -1
FIRE_CORAL: -1
FIRE_CORAL_BLOCK: -1
FIRE_CORAL_FAN: -1
FIRE_CORAL_WALL_FAN: -1
FIREWORK_ROCKET: -1
FIREWORK_STAR: -1
FISHING_ROD: -1
FLETCHING_TABLE: -1
FLINT: -1
FLINT_AND_STEEL: -1
FLOWER_BANNER_PATTERN: -1
FLOWER_POT: -1
FOX_SPAWN_EGG: -1
FROSTED_ICE: -1
FURNACE: -1
FURNACE_MINECART: -1
GHAST_SPAWN_EGG: -1
GHAST_TEAR: -1
GLASS: -1
GLASS_BOTTLE: -1
GLASS_PANE: -1
GLISTERING_MELON_SLICE: -1
GLOBE_BANNER_PATTERN: -1
GLOWSTONE: -1
GLOWSTONE_DUST: -1
GOLD_BLOCK: -1
GOLD_INGOT: -1
GOLD_NUGGET: -1
GOLD_ORE: -1
GOLDEN_APPLE: -1
GOLDEN_AXE: -1
GOLDEN_BOOTS: -1
GOLDEN_CARROT: -1
GOLDEN_CHESTPLATE: -1
GOLDEN_HELMET: -1
GOLDEN_HOE: -1
GOLDEN_HORSE_ARMOR: -1
GOLDEN_LEGGINGS: -1
GOLDEN_PICKAXE: -1
GOLDEN_SHOVEL: -1
GOLDEN_SWORD: -1
GRANITE: -1
GRANITE_SLAB: -1
GRANITE_STAIRS: -1
GRANITE_WALL: -1
GRASS: -1
GRASS_BLOCK: -1
GRASS_PATH: -1
GRAVEL: -1
GRAY_BANNER: -1
GRAY_BED: -1
GRAY_CARPET: -1
GRAY_CONCRETE: -1
GRAY_CONCRETE_POWDER: -1
GRAY_DYE: -1
GRAY_GLAZED_TERRACOTTA: -1
GRAY_SHULKER_BOX: -1
GRAY_STAINED_GLASS: -1
GRAY_STAINED_GLASS_PANE: -1
GRAY_TERRACOTTA: -1
GRAY_WALL_BANNER: -1
GRAY_WOOL: -1
GREEN_BANNER: -1
GREEN_BED: -1
GREEN_CARPET: -1
GREEN_CONCRETE: -1
GREEN_CONCRETE_POWDER: -1
GREEN_DYE: -1
GREEN_GLAZED_TERRACOTTA: -1
GREEN_SHULKER_BOX: -1
GREEN_STAINED_GLASS: -1
GREEN_STAINED_GLASS_PANE: -1
GREEN_TERRACOTTA: -1
GREEN_WALL_BANNER: -1
GREEN_WOOL: -1
GRINDSTONE: -1
GUARDIAN_SPAWN_EGG: -1
GUNPOWDER: -1
HAY_BLOCK: -1
HEART_OF_THE_SEA: -1
HEAVY_WEIGHTED_PRESSURE_PLATE: -1
HONEY_BLOCK: -1
HONEY_BOTTLE: -1
HONEYCOMB: -1
HONEYCOMB_BLOCK: -1
HOPPER: -1
HOPPER_MINECART: -1
HORN_CORAL: -1
HORN_CORAL_BLOCK: -1
HORN_CORAL_FAN: -1
HORN_CORAL_WALL_FAN: -1
HORSE_SPAWN_EGG: -1
HUSK_SPAWN_EGG: -1
ICE: -1
INFESTED_CHISELED_STONE_BRICKS: -1
INFESTED_COBBLESTONE: -1
INFESTED_CRACKED_STONE_BRICKS: -1
INFESTED_MOSSY_STONE_BRICKS: -1
INFESTED_STONE: -1
INFESTED_STONE_BRICKS: -1
INK_SAC: -1
IRON_AXE: -1
IRON_BARS: -1
IRON_BLOCK: -1
IRON_BOOTS: -1
IRON_CHESTPLATE: -1
IRON_DOOR: -1
IRON_HELMET: -1
IRON_HOE: -1
IRON_HORSE_ARMOR: -1
IRON_INGOT: -1
IRON_LEGGINGS: -1
IRON_NUGGET: -1
IRON_ORE: -1
IRON_PICKAXE: -1
IRON_SHOVEL: -1
IRON_SWORD: -1
IRON_TRAPDOOR: -1
ITEM_FRAME: -1
JACK_O_LANTERN: -1
JIGSAW: -1
JUKEBOX: -1
JUNGLE_BOAT: -1
JUNGLE_BUTTON: -1
JUNGLE_DOOR: -1
JUNGLE_FENCE: -1
JUNGLE_FENCE_GATE: -1
JUNGLE_LEAVES: -1
JUNGLE_LOG: -1
JUNGLE_PLANKS: -1
JUNGLE_PRESSURE_PLATE: -1
JUNGLE_SAPLING: -1
JUNGLE_SIGN: -1
JUNGLE_SLAB: -1
JUNGLE_STAIRS: -1
JUNGLE_TRAPDOOR: -1
JUNGLE_WALL_SIGN: -1
JUNGLE_WOOD: -1
KELP: -1
KELP_PLANT: -1
KNOWLEDGE_BOOK: -1
LADDER: -1
LANTERN: -1
LAPIS_BLOCK: -1
LAPIS_LAZULI: -1
LAPIS_ORE: -1
LARGE_FERN: -1
LAVA: -1
LAVA_BUCKET: -1
LEAD: -1
LEATHER: -1
LEATHER_BOOTS: -1
LEATHER_CHESTPLATE: -1
LEATHER_HELMET: -1
LEATHER_HORSE_ARMOR: -1
LEATHER_LEGGINGS: -1
LECTERN: -1
LEVER: -1
LIGHT_BLUE_BANNER: -1
LIGHT_BLUE_BED: -1
LIGHT_BLUE_CARPET: -1
LIGHT_BLUE_CONCRETE: -1
LIGHT_BLUE_CONCRETE_POWDER: -1
LIGHT_BLUE_DYE: -1
LIGHT_BLUE_GLAZED_TERRACOTTA: -1
LIGHT_BLUE_SHULKER_BOX: -1
LIGHT_BLUE_STAINED_GLASS: -1
LIGHT_BLUE_STAINED_GLASS_PANE: -1
LIGHT_BLUE_TERRACOTTA: -1
LIGHT_BLUE_WALL_BANNER: -1
LIGHT_BLUE_WOOL: -1
LIGHT_GRAY_BANNER: -1
LIGHT_GRAY_BED: -1
LIGHT_GRAY_CARPET: -1
LIGHT_GRAY_CONCRETE: -1
LIGHT_GRAY_CONCRETE_POWDER: -1
LIGHT_GRAY_DYE: -1
LIGHT_GRAY_GLAZED_TERRACOTTA: -1
LIGHT_GRAY_SHULKER_BOX: -1
LIGHT_GRAY_STAINED_GLASS: -1
LIGHT_GRAY_STAINED_GLASS_PANE: -1
LIGHT_GRAY_TERRACOTTA: -1
LIGHT_GRAY_WALL_BANNER: -1
LIGHT_GRAY_WOOL: -1
LIGHT_WEIGHTED_PRESSURE_PLATE: -1
LILAC: -1
LILY_OF_THE_VALLEY: -1
LILY_PAD: -1
LIME_BANNER: -1
LIME_BED: -1
LIME_CARPET: -1
LIME_CONCRETE: -1
LIME_CONCRETE_POWDER: -1
LIME_DYE: -1
LIME_GLAZED_TERRACOTTA: -1
LIME_SHULKER_BOX: -1
LIME_STAINED_GLASS: -1
LIME_STAINED_GLASS_PANE: -1
LIME_TERRACOTTA: -1
LIME_WALL_BANNER: -1
LIME_WOOL: -1
LINGERING_POTION: -1
LLAMA_SPAWN_EGG: -1
LOOM: -1
MAGENTA_BANNER: -1
MAGENTA_BED: -1
MAGENTA_CARPET: -1
MAGENTA_CONCRETE: -1
MAGENTA_CONCRETE_POWDER: -1
MAGENTA_DYE: -1
MAGENTA_GLAZED_TERRACOTTA: -1
MAGENTA_SHULKER_BOX: -1
MAGENTA_STAINED_GLASS: -1
MAGENTA_STAINED_GLASS_PANE: -1
MAGENTA_TERRACOTTA: -1
MAGENTA_WALL_BANNER: -1
MAGENTA_WOOL: -1
MAGMA_BLOCK: -1
MAGMA_CREAM: -1
MAGMA_CUBE_SPAWN_EGG: -1
MAP: -1
MELON: -1
MELON_SEEDS: -1
MELON_SLICE: -1
MELON_STEM: -1
MILK_BUCKET: -1
MINECART: -1
MOJANG_BANNER_PATTERN: -1
MOOSHROOM_SPAWN_EGG: -1
MOSSY_COBBLESTONE: -1
MOSSY_COBBLESTONE_SLAB: -1
MOSSY_COBBLESTONE_STAIRS: -1
MOSSY_COBBLESTONE_WALL: -1
MOSSY_STONE_BRICK_SLAB: -1
MOSSY_STONE_BRICK_STAIRS: -1
MOSSY_STONE_BRICK_WALL: -1
MOSSY_STONE_BRICKS: -1
MOVING_PISTON: -1
MULE_SPAWN_EGG: -1
MUSHROOM_STEM: -1
MUSHROOM_STEW: -1
MUSIC_DISC_11: -1
MUSIC_DISC_13: -1
MUSIC_DISC_BLOCKS: -1
MUSIC_DISC_CAT: -1
MUSIC_DISC_CHIRP: -1
MUSIC_DISC_FAR: -1
MUSIC_DISC_MALL: -1
MUSIC_DISC_MELLOHI: -1
MUSIC_DISC_STAL: -1
MUSIC_DISC_STRAD: -1
MUSIC_DISC_WAIT: -1
MUSIC_DISC_WARD: -1
MUTTON: -1
MYCELIUM: -1
NAME_TAG: -1
NAUTILUS_SHELL: -1
NETHER_BRICK: -1
NETHER_BRICK_FENCE: -1
NETHER_BRICK_SLAB: -1
NETHER_BRICK_STAIRS: -1
NETHER_BRICK_WALL: -1
NETHER_BRICKS: -1
NETHER_PORTAL: -1
NETHER_QUARTZ_ORE: -1
NETHER_STAR: -1
NETHER_WART: -1
NETHER_WART_BLOCK: -1
NETHERRACK: -1
NOTE_BLOCK: -1
OAK_BOAT: -1
OAK_BUTTON: -1
OAK_DOOR: -1
OAK_FENCE: -1
OAK_FENCE_GATE: -1
OAK_LEAVES: -1
OAK_LOG: -1
OAK_PLANKS: -1
OAK_PRESSURE_PLATE: -1
OAK_SAPLING: -1
OAK_SIGN: -1
OAK_SLAB: -1
OAK_STAIRS: -1
OAK_TRAPDOOR: -1
OAK_WALL_SIGN: -1
OAK_WOOD: -1
OBSERVER: -1
OBSIDIAN: -1
OCELOT_SPAWN_EGG: -1
ORANGE_BANNER: -1
ORANGE_BED: -1
ORANGE_CARPET: -1
ORANGE_CONCRETE: -1
ORANGE_CONCRETE_POWDER: -1
ORANGE_DYE: -1
ORANGE_GLAZED_TERRACOTTA: -1
ORANGE_SHULKER_BOX: -1
ORANGE_STAINED_GLASS: -1
ORANGE_STAINED_GLASS_PANE: -1
ORANGE_TERRACOTTA: -1
ORANGE_TULIP: -1
ORANGE_WALL_BANNER: -1
ORANGE_WOOL: -1
OXEYE_DAISY: -1
PACKED_ICE: -1
PAINTING: -1
PANDA_SPAWN_EGG: -1
PAPER: -1
PARROT_SPAWN_EGG: -1
PEONY: -1
PETRIFIED_OAK_SLAB: -1
PHANTOM_MEMBRANE: -1
PHANTOM_SPAWN_EGG: -1
PIG_SPAWN_EGG: -1
PILLAGER_SPAWN_EGG: -1
PINK_BANNER: -1
PINK_BED: -1
PINK_CARPET: -1
PINK_CONCRETE: -1
PINK_CONCRETE_POWDER: -1
PINK_DYE: -1
PINK_GLAZED_TERRACOTTA: -1
PINK_SHULKER_BOX: -1
PINK_STAINED_GLASS: -1
PINK_STAINED_GLASS_PANE: -1
PINK_TERRACOTTA: -1
PINK_TULIP: -1
PINK_WALL_BANNER: -1
PINK_WOOL: -1
PISTON: -1
PISTON_HEAD: -1
PLAYER_HEAD: -1
PLAYER_WALL_HEAD: -1
PODZOL: -1
POISONOUS_POTATO: -1
POLAR_BEAR_SPAWN_EGG: -1
POLISHED_ANDESITE: -1
POLISHED_ANDESITE_SLAB: -1
POLISHED_ANDESITE_STAIRS: -1
POLISHED_DIORITE: -1
POLISHED_DIORITE_SLAB: -1
POLISHED_DIORITE_STAIRS: -1
POLISHED_GRANITE: -1
POLISHED_GRANITE_SLAB: -1
POLISHED_GRANITE_STAIRS: -1
POPPED_CHORUS_FRUIT: -1
POPPY: -1
PORKCHOP: -1
POTATO: -1
POTATOES: -1
POTION: -1
POTTED_ACACIA_SAPLING: -1
POTTED_ALLIUM: -1
POTTED_AZURE_BLUET: -1
POTTED_BAMBOO: -1
POTTED_BIRCH_SAPLING: -1
POTTED_BLUE_ORCHID: -1
POTTED_BROWN_MUSHROOM: -1
POTTED_CACTUS: -1
POTTED_CORNFLOWER: -1
POTTED_DANDELION: -1
POTTED_DARK_OAK_SAPLING: -1
POTTED_DEAD_BUSH: -1
POTTED_FERN: -1
POTTED_JUNGLE_SAPLING: -1
POTTED_LILY_OF_THE_VALLEY: -1
POTTED_OAK_SAPLING: -1
POTTED_ORANGE_TULIP: -1
POTTED_OXEYE_DAISY: -1
POTTED_PINK_TULIP: -1
POTTED_POPPY: -1
POTTED_RED_MUSHROOM: -1
POTTED_RED_TULIP: -1
POTTED_SPRUCE_SAPLING: -1
POTTED_WHITE_TULIP: -1
POTTED_WITHER_ROSE: -1
POWERED_RAIL: -1
PRISMARINE: -1
PRISMARINE_BRICK_SLAB: -1
PRISMARINE_BRICK_STAIRS: -1
PRISMARINE_BRICKS: -1
PRISMARINE_CRYSTALS: -1
PRISMARINE_SHARD: -1
PRISMARINE_SLAB: -1
PRISMARINE_STAIRS: -1
PRISMARINE_WALL: -1
PUFFERFISH: -1
PUFFERFISH_BUCKET: -1
PUFFERFISH_SPAWN_EGG: -1
PUMPKIN: -1
PUMPKIN_PIE: -1
PUMPKIN_SEEDS: -1
PUMPKIN_STEM: -1
PURPLE_BANNER: -1
PURPLE_BED: -1
PURPLE_CARPET: -1
PURPLE_CONCRETE: -1
PURPLE_CONCRETE_POWDER: -1
PURPLE_DYE: -1
PURPLE_GLAZED_TERRACOTTA: -1
PURPLE_SHULKER_BOX: -1
PURPLE_STAINED_GLASS: -1
PURPLE_STAINED_GLASS_PANE: -1
PURPLE_TERRACOTTA: -1
PURPLE_WALL_BANNER: -1
PURPLE_WOOL: -1
PURPUR_BLOCK: -1
PURPUR_PILLAR: -1
PURPUR_SLAB: -1
PURPUR_STAIRS: -1
QUARTZ: -1
QUARTZ_BLOCK: -1
QUARTZ_PILLAR: -1
QUARTZ_SLAB: -1
QUARTZ_STAIRS: -1
RABBIT: -1
RABBIT_FOOT: -1
RABBIT_HIDE: -1
RABBIT_SPAWN_EGG: -1
RABBIT_STEW: -1
RAIL: -1
RAVAGER_SPAWN_EGG: -1
RED_BANNER: -1
RED_BED: -1
RED_CARPET: -1
RED_CONCRETE: -1
RED_CONCRETE_POWDER: -1
RED_DYE: -1
RED_GLAZED_TERRACOTTA: -1
RED_MUSHROOM: -1
RED_MUSHROOM_BLOCK: -1
RED_NETHER_BRICK_SLAB: -1
RED_NETHER_BRICK_STAIRS: -1
RED_NETHER_BRICK_WALL: -1
RED_NETHER_BRICKS: -1
RED_SAND: -1
RED_SANDSTONE: -1
RED_SANDSTONE_SLAB: -1
RED_SANDSTONE_STAIRS: -1
RED_SANDSTONE_WALL: -1
RED_SHULKER_BOX: -1
RED_STAINED_GLASS: -1
RED_STAINED_GLASS_PANE: -1
RED_TERRACOTTA: -1
RED_TULIP: -1
RED_WALL_BANNER: -1
RED_WOOL: -1
REDSTONE: -1
REDSTONE_BLOCK: -1
REDSTONE_LAMP: -1
REDSTONE_ORE: -1
REDSTONE_TORCH: -1
REDSTONE_WALL_TORCH: -1
REDSTONE_WIRE: -1
REPEATER: -1
REPEATING_COMMAND_BLOCK: -1
ROSE_BUSH: -1
ROTTEN_FLESH: -1
SADDLE: -1
SALMON: -1
SALMON_BUCKET: -1
SALMON_SPAWN_EGG: -1
SAND: -1
SANDSTONE: -1
SANDSTONE_SLAB: -1
SANDSTONE_STAIRS: -1
SANDSTONE_WALL: -1
SCAFFOLDING: -1
SCUTE: -1
SEA_LANTERN: -1
SEA_PICKLE: -1
SEAGRASS: -1
SHEARS: -1
SHEEP_SPAWN_EGG: -1
SHIELD: -1
SHULKER_BOX: -1
SHULKER_SHELL: -1
SHULKER_SPAWN_EGG: -1
SILVERFISH_SPAWN_EGG: -1
SKELETON_HORSE_SPAWN_EGG: -1
SKELETON_SKULL: -1
SKELETON_SPAWN_EGG: -1
SKELETON_WALL_SKULL: -1
SKULL_BANNER_PATTERN: -1
SLIME_BALL: -1
SLIME_BLOCK: -1
SLIME_SPAWN_EGG: -1
SMITHING_TABLE: -1
SMOKER: -1
SMOOTH_QUARTZ: -1
SMOOTH_QUARTZ_SLAB: -1
SMOOTH_QUARTZ_STAIRS: -1
SMOOTH_RED_SANDSTONE: -1
SMOOTH_RED_SANDSTONE_SLAB: -1
SMOOTH_RED_SANDSTONE_STAIRS: -1
SMOOTH_SANDSTONE: -1
SMOOTH_SANDSTONE_SLAB: -1
SMOOTH_SANDSTONE_STAIRS: -1
SMOOTH_STONE: -1
SMOOTH_STONE_SLAB: -1
SNOW: -1
SNOW_BLOCK: -1
SNOWBALL: -1
SOUL_SAND: -1
SPAWNER: -1
SPECTRAL_ARROW: -1
SPIDER_EYE: -1
SPIDER_SPAWN_EGG: -1
SPLASH_POTION: -1
SPONGE: -1
SPRUCE_BOAT: -1
SPRUCE_BUTTON: -1
SPRUCE_DOOR: -1
SPRUCE_FENCE: -1
SPRUCE_FENCE_GATE: -1
SPRUCE_LEAVES: -1
SPRUCE_LOG: -1
SPRUCE_PLANKS: -1
SPRUCE_PRESSURE_PLATE: -1
SPRUCE_SAPLING: -1
SPRUCE_SIGN: -1
SPRUCE_SLAB: -1
SPRUCE_STAIRS: -1
SPRUCE_TRAPDOOR: -1
SPRUCE_WALL_SIGN: -1
SPRUCE_WOOD: -1
SQUID_SPAWN_EGG: -1
STICK: -1
STICKY_PISTON: -1
STONE: -1
STONE_AXE: -1
STONE_BRICK_SLAB: -1
STONE_BRICK_STAIRS: -1
STONE_BRICK_WALL: -1
STONE_BRICKS: -1
STONE_BUTTON: -1
STONE_HOE: -1
STONE_PICKAXE: -1
STONE_PRESSURE_PLATE: -1
STONE_SHOVEL: -1
STONE_SLAB: -1
STONE_STAIRS: -1
STONE_SWORD: -1
STONECUTTER: -1
STRAY_SPAWN_EGG: -1
STRING: -1
STRIPPED_ACACIA_LOG: -1
STRIPPED_ACACIA_WOOD: -1
STRIPPED_BIRCH_LOG: -1
STRIPPED_BIRCH_WOOD: -1
STRIPPED_DARK_OAK_LOG: -1
STRIPPED_DARK_OAK_WOOD: -1
STRIPPED_JUNGLE_LOG: -1
STRIPPED_JUNGLE_WOOD: -1
STRIPPED_OAK_LOG: -1
STRIPPED_OAK_WOOD: -1
STRIPPED_SPRUCE_LOG: -1
STRIPPED_SPRUCE_WOOD: -1
STRUCTURE_BLOCK: -1
STRUCTURE_VOID: -1
SUGAR: -1
SUGAR_CANE: -1
SUNFLOWER: -1
SUSPICIOUS_STEW: -1
SWEET_BERRIES: -1
SWEET_BERRY_BUSH: -1
TALL_GRASS: -1
TALL_SEAGRASS: -1
TERRACOTTA: -1
TIPPED_ARROW: -1
TNT: -1
TNT_MINECART: -1
TORCH: -1
TOTEM_OF_UNDYING: -1
TRADER_LLAMA_SPAWN_EGG: -1
TRAPPED_CHEST: -1
TRIDENT: -1
TRIPWIRE: -1
TRIPWIRE_HOOK: -1
TROPICAL_FISH: -1
TROPICAL_FISH_BUCKET: -1
TROPICAL_FISH_SPAWN_EGG: -1
TUBE_CORAL: -1
TUBE_CORAL_BLOCK: -1
TUBE_CORAL_FAN: -1
TUBE_CORAL_WALL_FAN: -1
TURTLE_EGG: -1
TURTLE_HELMET: -1
TURTLE_SPAWN_EGG: -1
VEX_SPAWN_EGG: -1
VILLAGER_SPAWN_EGG: -1
VINDICATOR_SPAWN_EGG: -1
VINE: -1
VOID_AIR: -1
WALL_TORCH: -1
WANDERING_TRADER_SPAWN_EGG: -1
WATER: -1
WATER_BUCKET: -1
WET_SPONGE: -1
WHEAT: -1
WHEAT_SEEDS: -1
WHITE_BANNER: -1
WHITE_BED: -1
WHITE_CARPET: -1
WHITE_CONCRETE: -1
WHITE_CONCRETE_POWDER: -1
WHITE_DYE: -1
WHITE_GLAZED_TERRACOTTA: -1
WHITE_SHULKER_BOX: -1
WHITE_STAINED_GLASS: -1
WHITE_STAINED_GLASS_PANE: -1
WHITE_TERRACOTTA: -1
WHITE_TULIP: -1
WHITE_WALL_BANNER: -1
WHITE_WOOL: -1
WITCH_SPAWN_EGG: -1
WITHER_ROSE: -1
WITHER_SKELETON_SKULL: -1
WITHER_SKELETON_SPAWN_EGG: -1
WITHER_SKELETON_WALL_SKULL: -1
WOLF_SPAWN_EGG: -1
WOODEN_AXE: -1
WOODEN_HOE: -1
WOODEN_PICKAXE: -1
WOODEN_SHOVEL: -1
WOODEN_SWORD: -1
WRITABLE_BOOK: -1
WRITTEN_BOOK: -1
YELLOW_BANNER: -1
YELLOW_BED: -1
YELLOW_CARPET: -1
YELLOW_CONCRETE: -1
YELLOW_CONCRETE_POWDER: -1
YELLOW_DYE: -1
YELLOW_GLAZED_TERRACOTTA: -1
YELLOW_SHULKER_BOX: -1
YELLOW_STAINED_GLASS: -1
YELLOW_STAINED_GLASS_PANE: -1
YELLOW_TERRACOTTA: -1
YELLOW_WALL_BANNER: -1
YELLOW_WOOL: -1
ZOMBIE_HEAD: -1
ZOMBIE_HORSE_SPAWN_EGG: -1
ZOMBIE_PIGMAN_SPAWN_EGG: -1
ZOMBIE_SPAWN_EGG: -1
ZOMBIE_VILLAGER_SPAWN_EGG: -1
ZOMBIE_WALL_HEAD: -1
