# Default Config File for Dynamic Shops Plugin
# GUI enables or disables the GUI feature of the shops.
# Default Modifier: 1% change as a decimal per sale to 3 dp; eg. 0.001 but not 0.0001
# Prices: use "/dsa set name price" to enable or /dsa set [price] on held item

message: Dynamic Shops plugin Developed by idiotonastic.

GUI: true
Calculate_from_raw: true
transaction_modifier: 0.01
crafting_modifier: 0.1