main: com.hotmail.idiotonastic.plugins.TrulyDynamicShops.Main
name: TrulyDynamicShops
version: 3.0
api-version: 1.15
author: idiotonastic
depend: [ Vault ]

commands:
    Shop:
        description: opens GUI based buy screen if GUI enabled
    Sell:
        description: opens GUI based sell screen if GUI enabled
    Price:
        description: returns Price of item.
    TDS:
        description: Administration commands.

permissions:
    trulydynamicshops.admin:
        description: Players with this node have all dynamicshops permissions.
        default: op
    trulydynamicshops.cantrade:
        description: Players with this node can buy and sell items
        default: true